import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Explore Art",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark:bg-gray-300">
      
      <body className={inter.className}>
      <Navbar />
      {children}
      </body>
      <Footer />
    </html>
  );
}
